### ISSUE TITLE
3: a(done), b(done), c(done), d(done), e(todo)

### ISSUE THREAD

**Issue by obonobo** [obonobo/soen363-databases#10]

**Comment by JustinLohKingWei** [comment]
working on 3a ,3b

**Comment by instamine** [comment]
What have you accomplished so far ?

**Comment by instamine** [comment]
@JustinLohKingWei you finished 3a,3b,3c,3d, 3I 

Did you start 3-E ?

**Comment by obonobo** [comment]
## COMPLETED 

3a - 3d

## TODO

3e
